import * as mongoose from 'mongoose';

export const CharCTableSchema = new mongoose.Schema({
  mainView: String,
  collapseArmor: Boolean,
  showArmor: Boolean,
  showDamage: Boolean,

  name: {
    type: String,
    unique: true,
  },
  _id: {
    type: String,
    unique: true,
  },
  str: Number,
  sta: Number,
  dex: Number,
  per: Number,
  ref: Number,
  will: Number,
  athletics: Number,
  vigorBonus: Number,
  moveBonus: Number,
  weaponWeight: Number,
  vigorSpent: Number,
  toughness: Number,
  toughnessSpent: Number,
  heroicTurns: Number,
  heroicTurnsSpent: Number,
  heroicTurnsMultiplier: Number,

  maxMana: Number,
  manaSpent: Number,
  manaReg: Number,
  bonusMana: Number,
  currentMana: Number,

  evade: Number,
  attack: Number,
  block: Number,
  defBonus: Number,

  weaponSkill: Number,
  shieldSkill: Number,
  shieldDef: Number,
  shieldHP: Number,
  shieldDMG: Number,
  shieldHPLeft: Number,
  evadeSkill: Number,

  headWeight: Number,
  breastWeight: Number,
  lArmWeight: Number,
  rArmWeight: Number,
  lLegWeight: Number,
  rLegWeight: Number,
  shieldWeight: Number,

  pHeadWeight: Number,
  pBreastWeight: Number,
  pLArmWeight: Number,
  pRArmWeight: Number,
  pLLegWeight: Number,
  pRLegWeight: Number,

  headArmor: Number,
  breastArmor: Number,
  lArmArmor: Number,
  rArmArmor: Number,
  lLegArmor: Number,
  rLegArmor: Number,

  paddingHeadArmor: Number,
  paddingBreastArmor: Number,
  paddingLArmArmor: Number,
  paddingRArmArmor: Number,
  paddingLLegArmor: Number,
  paddingRLegArmor: Number,

  sunderHeadArmor: Number,
  sunderBreastArmor: Number,
  sunderLArmArmor: Number,
  sunderRArmArmor: Number,
  sunderLLegArmor: Number,
  sunderRLegArmor: Number,

  sunderPaddingHeadArmor: Number,
  sunderPaddingBreastArmor: Number,
  sunderPaddingLArmArmor: Number,
  sunderPaddingRArmArmor: Number,
  sunderPaddingLLegArmor: Number,
  sunderPaddingRLegArmor: Number,

  encumbrance: Number,
  move: Number,
  bonusEnc: Number,
  maxVigor: Number,
  hp: Number,
  hpLeft: Number,

  dmgTH: Number,
  dmgTB: Number,
  dmgTLA: Number,
  dmgTRA: Number,
  dmgTLL: Number,
  dmgTRL: Number,

  dmgBH: Number,
  dmgBB: Number,
  dmgBLA: Number,
  dmgBRA: Number,
  dmgBLL: Number,
  dmgBRL: Number,

  dmgCH: Number,
  dmgCB: Number,
  dmgCLA: Number,
  dmgCRA: Number,
  dmgCLL: Number,
  dmgCRL: Number,

  dmgFH: Number,
  dmgFB: Number,
  dmgFLA: Number,
  dmgFRA: Number,
  dmgFLL: Number,
  dmgFRL: Number,

  minusAtt: Number,
  minusDef: Number,
  minusMove: Number,
  plusVigorCost: Number,
  penalty: Number,
}).index({ name: 1 });
